packages:
  - jupyter-panel-proxy
channels:
  - defaults
  - conda-forge
  - pyviz
  - javascript
dependencies:
  - folium=0.12.1
  - panel
  - numpy
  - pandas
  - python=3.9
  - bokeh=2.4.2
  - conda-forge
  - nodejs=16.13.*
  - flask
  - pip
  - pip:
    - Flask-Testing
