packages:
  - jupyter-panel-proxy
channels:
  - javascript
  - pyviz
dependencies:
  - folium=0.12.1
  - panel=0.12.1
  - numpy
  - pandas
  - python=3.9
  - bokeh=2.4.2
  - conda-forge::numpy=1.21.*
  - nodejs=16.13.*
  - flask
  - pip
  - pip:
    - Flask-Testing


