channels:
  - defaults
  - conda-forge
  - pyviz
  - javascript

dependencies:
  - folium=0.12.1
  - panel=0.12.2  # Updated to a version compatible with Bokeh 2.4.2
  - numpy  # Let Conda choose the appropriate version
  - pandas
  - python=3.9
  - bokeh=2.4.2
  - conda-forge::nodejs=16.13.*
  - flask
  - pip
  - pip:
    - Flask-Testing
    - jupyter-panel-proxy
